version: '3'
services:
  # db:
    # container_name: postgres_django
    # image: postgres
  web:
    build: .
    command: ["sh", "./start.sh"]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    # depends_on:
      # - db