# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Fotos(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, caption: str=None):  # noqa: E501
        """Fotos - a model defined in Swagger

        :param url: The url of this Fotos.  # noqa: E501
        :type url: str
        :param caption: The caption of this Fotos.  # noqa: E501
        :type caption: str
        """
        self.swagger_types = {
            'url': str,
            'caption': str
        }

        self.attribute_map = {
            'url': 'url',
            'caption': 'caption'
        }

        self._url = url
        self._caption = caption

    @classmethod
    def from_dict(cls, dikt) -> 'Fotos':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Fotos of this Fotos.  # noqa: E501
        :rtype: Fotos
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Fotos.


        :return: The url of this Fotos.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Fotos.


        :param url: The url of this Fotos.
        :type url: str
        """

        self._url = url

    @property
    def caption(self) -> str:
        """Gets the caption of this Fotos.


        :return: The caption of this Fotos.
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption: str):
        """Sets the caption of this Fotos.


        :param caption: The caption of this Fotos.
        :type caption: str
        """

        self._caption = caption
