# Generated by Django 2.2.1 on 2019-06-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(verbose_name='Cuerpo de la noticia'),
        ),
    ]
