# Generated by Django 2.2.1 on 2019-06-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190621_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='tittle',
            new_name='title',
        ),
    ]
