# Generated by Django 2.2.2 on 2019-06-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(verbose_name='Semestre')),
                ('subject', models.CharField(max_length=150, verbose_name='Asignatura')),
                ('ffile', models.FileField(upload_to='media', verbose_name='Archivo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Material de Apoyo',
                'verbose_name_plural': 'Materiales de Apoyo',
            },
        ),
    ]
